# reference: http://www.objc.io/issue-6/travis-ci.html

# whitelist
branches:
  only:
    - master
language: objective-c
osx_image: xcode7.1
env:
    matrix:
    - TEST_SDK=iphonesimulator9.1 OS=8.4
    - TEST_SDK=iphonesimulator9.1 OS=9.1
script:
- xctool test -test-sdk $TEST_SDK -destination "name=iPhone 6,OS=$OS" -sdk iphonesimulator -workspace Example/PINRemoteImage.xcworkspace -scheme PINRemoteImage ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
